version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: fibershare_db
    environment:
      POSTGRES_USER: fibershare
      POSTGRES_PASSWORD: fibershare123
      POSTGRES_DB: fibershare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 